### ISSUE TITLE
Fuziona con .json

### ISSUE THREAD

**Issue by killerbossoriginal** [GalaxyVinci05/map.db#1]
Funziona se uno al posto di mettere .db mettesse .json?

**Comment by GalaxyVinci05** [comment]
@killerbossoriginal certo, map.db scrive i dati in formato JSON in un file e li legge con il parser JSON integrato, quindi dovrà soltanto leggere il testo all'interno del file, qualunque estensione esso abbia.

**Comment by killerbossoriginal** [comment]
ok, grazie

Il lun 10 gen 2022, 23:13 GalaxyVinci05 ***@***.***> ha
scritto:

**Comment by GalaxyVinci05** [comment]
Di niente, se non hai altre domande al riguardo chiudo l'issue

**Comment by killerbossoriginal** [comment]
> Di niente, se non hai altre domande al riguardo chiudo l'issue

Va bene, grazie
